# Add 'Documentation' label to any change to .md files within the entire repository 
Documentation:
- changed-files:
  - any-glob-to-any-file: '*.md'

# Add 'release' label to any PR that is opened against the `main` branch
release:
 - base-branch: 'main'
